version: '3.2'

services:
  php:
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - ./quarto:/quarto
    depends_on:
      - postgres
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./quarto:/quarto
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=quarto
      - POSTGRES_PASSWORD=quarto
      - POSTGRES_DB=quarto
    ports:
        - "5433:5432"
    expose:
        - "5432"
    volumes:
      - quarto-pg-data:/var/lib/postgresql/data
volumes:
  quarto-pg-data: {}
