version: '2'

services:
  service_php:
    build: docker/php
    tty: true
    labels:
      kompose.service.type: nodeport
    ports:
      - 9000:9000
    volumes:
      - ./quarto:/quarto

  service_nginx:
    image: nginx:alpine
    ports:
      - "8081:8081"
    volumes:
      - ./quarto:/quarto
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  service_postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
        - "5433:5432"
    expose:
      - 5433
    volumes:
      - ./quarto/var/data:/var/lib/postgresql/data