version: '3.2'

services:
  php:
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - ./quarto:/quarto
    depends_on:
      - postgres
  nginx:
    image: nginx:alpine
    ports:
      - "8081:8081"
    volumes:
      - ./quarto:/quarto
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=quatro
      - POSTGRES_PASSWORD=quatro
      - POSTGRES_DB=quatro
    ports:
        - "5433:5432"
    volumes:
      - quatro-pg-data:/var/lib/postgresql/data
volumes:
  quatro-pg-data: {}
