index:
  path: /
  defaults: { _controller: 'App\Controller\MainController::start' }

game:
    resource: '../src/Controller/GamePage/gameRouting.yml'
    prefix:   /game

gameapi:
    resource: '../src/Controller/GameApi/gameApiRouting.yml'
    prefix:   /gameapi

gameapi_new:
  path: /gameapi
  controller: 'App\Controller\GameApi\GameApiController::new'


all:
  path: /{req}
  defaults: { _controller: 'App\Controller\DefaultController::index' }
  requirements:
      req: ".+"
