index:
  path: /
  defaults: { _controller: 'App\Controller\MainController::start' }

game_new:
  path: /game
  controller: 'App\Controller\GameController::new'

game:
  path: /game/{id_game}
  controller: 'App\Controller\GameController::current'
  requirements:
        id_game: '\d+'

game_select:
  path: /game/{id_game}/select/{piece}
  defaults: { _controller: 'App\Controller\GameController::select' }

game_place:
  path: /game/{id_game}/place/{x}/{y}
  defaults: { _controller: 'App\Controller\GameController::place' }