index:
  path: /
  defaults: { _controller: 'App\Controller\MainController::start' }

game_new:
  path: /game
  controller: 'App\Controller\GameController::new'

game:
  path: /game/{id_game}
  controller: 'App\Controller\GameController::current'
  requirements:
        id_game: '\d+'

